sudo: required

language: generic
services:
  - rabbitmq
before_script:
  - sudo rabbitmqctl add_user kpc
  - sudo rabbitmqctl set_user_tags kpc administrator
  - sudo rabbitmqctl set_permissions -p / kpc ".*" ".*" ".*"
  - sudo rabbitmq-plugins enable rabbitmq_management
