sudo: required

language: python
python:
    - "3.6"
services:
  - rabbitmq
before_script:
  - sudo rabbitmqctl add_user kpc cpk
  - sudo rabbitmqctl set_user_tags "kpc" administrator
  - sudo rabbitmqctl set_permissions -p / kpc ".*" ".*" ".*"
  - sudo rabbitmq-plugins enable rabbitmq_management
script:
  - chmod +x test.sh
  - ./test.sh
  - echo 'server='$(./test.sh) >> config.cfg
  - cat config.cfg
  - pytest
after_failure:
  - cat MSBuild_*.failure.txt
