sudo: required

language: generic
services:
  - rabbitmq
before_script:
  - rabbitmqctl add_user user_name_to_be_defined associated_password_to_be_defined
  - rabbitmqctl set_user_tags user_name_to_be_defined administrator
  - rabbitmqctl set_permissions -p / kpc ".*" ".*" ".*"
  - rabbitmq-plugins enable rabbitmq_management
